package tower;

/**
 *
 * @author yamishi
 */
public class Sam extends javax.swing.JFrame {

    int num;
    Susan tawa = new Susan();

    public Sam() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nAros = new javax.swing.JTextField();
        boton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        han = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nmov = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Torres de Hanoi -- By Yamishi");
        setMinimumSize(new java.awt.Dimension(450, 320));
        setPreferredSize(new java.awt.Dimension(420, 350));
        getContentPane().setLayout(null);

        nAros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nArosActionPerformed(evt);
            }
        });
        getContentPane().add(nAros);
        nAros.setBounds(130, 30, 40, 30);

        boton.setText("RESOLVER");
        boton.setToolTipText("");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        getContentPane().add(boton);
        boton.setBounds(130, 70, 150, 40);

        han.setEditable(false);
        jScrollPane1.setViewportView(han);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 140, 280, 150);

        jLabel2.setText("Numero de aros");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 90, 20);

        jLabel3.setText("Procedimiento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 210, 80, 14);

        jLabel4.setText("Numero de movimientos");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 40, 140, 14);

        nmov.setEditable(false);
        getContentPane().add(nmov);
        nmov.setBounds(340, 30, 40, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        num = Integer.parseInt(nAros.getText());
        tawa.intDatos(num);
        han.setText(tawa.hanoi());
        nmov.setText(Integer.toString(tawa.mov()));
        tawa.reset();
        
    }//GEN-LAST:event_botonActionPerformed

    private void nArosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nArosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nArosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sam().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JTextPane han;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nAros;
    private javax.swing.JTextField nmov;
    // End of variables declaration//GEN-END:variables
}
